export const CHATS_FETCH_SUCCESS = "CHATS_FETCH_SUCCESS";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_ON_INIT = "AUTH_ON_INIT";
export const AUTH_ON_SUCCESS = "AUTH_ON_SUCCESS";
export const AUTH_ON_ERROR = "AUTH_ON_ERROR";
